# Setup
title: "Bruno Marinho"

# Use absolute URL when not hosting on the root of server

# url: ""
# baseurl: ""

url: "https://harkas.github.io"              # your host, for absolute URL
baseurl: "https://harkas.github.io/bruno" # the subpath of your site, e.g. /blog/  for example, '/blog' if your blog hosted on 'host/blog'

repository: "https://github.com/harkas/bruno"


markdown: kramdown
permalink: /writing/:title


navigation:
 - title: Home
   url: /
 - title: Writing
   url: /writing/
 - title: About
   url: /about/


# Assets

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed




port: 8989